### PR TITLE
Private Events 

### PR DESCRIPTION
**Pull request by Tekcoder**
**In this project, we were able to achieve the following** :

- Built and migrated the User, Event, Invitation model for the application
- Updated the README file to be descriptive and linked to this project.
- Created Users controller and corresponding routes for #new, #create, and #show actions. 
- Created a sign-up form for a new user and a simple #show page. 
- Added validations and authentication

### CODE REVIEW

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

Hi team :wave: 

I am not able to review your project because of this error, kindly look into. Here's a snapshot for 
reference purposes.

Screenshot from 2020-03-20 19-01-37

Rectify the issue, then submit another form for a code review.

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Inyama, Uchechukwu Henry ```

**Comment by KingsleyMcSimon** [comment]
Hi TSE,
This is really an old project and most of the required changes has been implemented. 
Pevents1
Pevents3
Pevents4
Pevents5

**Review by trekab — CHANGES_REQUESTED** [review]
### Changes Required! :recycle: 
Hi team, I was unable to fully review your project because of the error I got while trying to run your app. I have listed some changes you can make to improve your project;
- [ ] Add instructions for setting up the project locally in your `README.md` file. This would make it easier for visitors to check out your project. __[Note]__ Your getting started instructions are just highlighting the steps you took to build this project. This is irrelevant since it can be got from your commit messages.
- [ ] The link to the project on GitHub is redundant since for one to view the `README.md` file, they would already be on the project's GitHub page.
- [ ] Please configure linting for your project. ([linters-config](https://github.com/microverseinc/linters-config))
- [ ] I get this error when I try to create(sign up) a new user: Screenshot Please try to double-check that your app runs without errors before your next code review request. It usually helps to ask your coding partner to check it out and give you some feedback.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team    
#### Great Job so far, everything works fine, but there are a few more things required. 
### General 
- [x] This error occurs whenever I run migrations, it is the migration file that needs fixing.Let's fix this error .


### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by JasemDuncan** [comment]
Hello @kobiyoyo 
Thanks for your review. You are right, I tested in a new environment and I fixed that error.

Screen Shot 2020-10-13 at 01 33 36

Greetings,
@KingsleyMcSimon & @JasemDuncan

**Review by sumancrest0001 — APPROVED** [review]
**Status: Approved :100: :1st_place_medal: 
Congratulations @JasemDuncan :+1: :clap:** 
Thank you for making the change. Now, it is working properly and you can move to the next project. 
[optional] Currently, we need to login after signing up in the website. Instead of that, we can automatically log in a user when signed up correctly. It improves user experience.

**Pull request merged**
